# Generated by Django 3.1.5 on 2021-01-27 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=30)),
                ('razao_social', models.CharField(max_length=30)),
                ('cnpj', models.IntegerField()),
            ],
            options={
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='ItemNF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField(max_length=20)),
                ('valor_item', models.FloatField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=30)),
                ('unidade_produto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('valor_bruto', models.FloatField(max_length=40)),
                ('serie', models.IntegerField()),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultanf.empresa')),
                ('item_nf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultanf.itemnf')),
            ],
            options={
                'ordering': ['empresa'],
            },
        ),
        migrations.AddField(
            model_name='itemnf',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultanf.produto'),
        ),
    ]
