# Generated by Django 3.1.5 on 2021-01-27 20:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consultanf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nome_fantasia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razao_social',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemnf',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='ID único para o item', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemnf',
            name='peso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itemnf',
            name='valor_item',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='valor_bruto',
            field=models.IntegerField(),
        ),
    ]
